-- Plantilla legacy conservada por compatibilidad documental.
-- Para aplicar el hardening actual usar:
--
-- docs/sql/supervisor-hardening-v0.3.2.sql
--
-- No cerrar SELECT de stock_snapshots para anon desde esta plantilla:
-- el flujo actual de WhatsApp todavia usa lectura de snapshots recientes
-- para deduplicar antes de insertar.
